export const PKG_PREFIX = '@lightjs'
export const PKG_NAME = 'lightjs'
export const PKG_CAMELCASE_NAME = 'LightJS'
// export const PKG_CAMELCASE_LOCAL_NAME = 'ElementPlusLocale'
export const PKG_BRAND_NAME = 'Light JS'
